service: cron-jobs

provider:
  name: google
  stage: prod
  runtime: python37
  region: us-central1
  project: media-voice-applications
  # The GCF credentials can be a little tricky to set up. Luckily we've documented this for you here:
  # https://serverless.com/framework/docs/providers/google/guide/credentials/
  #
  # the path to the credentials file needs to be absolute
  credentials: /Users/milanarezina/PycharmProjects/wyzefind-core-api/cron_jobs/keyfile.json

  # Default is 60
  # TODO: Timeout flag doesn't work in GCP, need to manually go to function and edit it to increase timeout
  #  timeout: 120

plugins:
  - serverless-google-cloudfunctions

# needs more granular excluding in production as only the serverless provider npm
# package should be excluded (and not the whole node_modules directory)
package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  update_rss_articles:
    handler: update_rss_articles
    events:
      - http: path
